#!/usr/bin/env bash
set -euo pipefail

MANIFESTS_DIR="${MANIFESTS_DIR:-$(cd "$(dirname "$0")/../.." && pwd)/manifests}"
OUT="${OUT:-$(cd "$(dirname "$0")/.." && pwd)/measurements/measurements.yaml}"
CA_KEY="${CA_KEY:-$(cd "$(dirname "$0")/.." && pwd)/ca/operator_ca.key}"
CA_CRT="${CA_CRT:-$(cd "$(dirname "$0")/.." && pwd)/ca/operator_ca.crt}"

SGX_NFS=(nrf udr udm ausf pcf bsf nssf scp sepp smf)
TDX_NFS=(amf upf)

emit() { printf '%s\n' "$1" >> "$OUT"; }

: > "$OUT"
emit "# Auto-generated by build_measurements.sh"
emit "# Ground truth for NF measurements. Signed by operator CA."
emit "generated_at: \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\""
emit "sgx:"

for nf in "${SGX_NFS[@]}"; do
  sig="$MANIFESTS_DIR/open5gs-${nf}.sig"
  [[ -f "$sig" ]] || { echo "missing $sig" >&2; continue; }
  mr=$(gramine-sgx-sigstruct-view "$sig" 2>/dev/null | awk '/mr_enclave:/ {print $2}')
  mrs=$(gramine-sgx-sigstruct-view "$sig" 2>/dev/null | awk '/mr_signer:/ {print $2}')
  emit "  ${nf}:"
  emit "    mrenclave: \"${mr}\""
  emit "    mrsigner:  \"${mrs}\""
done

emit "tdx:"
for nf in "${TDX_NFS[@]}"; do
  emit "  ${nf}:"
  emit "    mrtd: \"PLACEHOLDER_SET_FROM_TDX_VM\""
done

if [[ -f "$CA_KEY" && -f "$CA_CRT" ]]; then
  sig_file="${OUT}.sig"
  openssl dgst -sha256 -sign "$CA_KEY" -out "$sig_file" "$OUT"
  echo "signed -> $sig_file"
else
  echo "CA not found; run gen_ca.sh first" >&2
fi

echo "wrote -> $OUT"
